
GET http://localhost:3000/

### 
POST http://localhost:3000/create
Content-Type: application/json

{
    "id": 1,
    "title": "SONIC 1",
    "genre": "Animação",
    "duration": 140 ,
    "age_rating": 10
}


### 
PUT http://localhost:3000/update/1
Content-Type: application/json

{
    "title": "Vingadores: Ultimato (Edição Estendida)",
    "genre": "Ação e Fantasia",
    "duration": 190,
    "age_rating": 14
}


### 
DELETE http://localhost:3000/delete/1