
GET http://localhost:3000/filmes


### 
POST http://localhost:3000/filmes
Content-Type: application/json

{
    "id": 13,
    "title": "Homem-Aranha: Através do Aranhaverso",
    "genre": "Animação",
    "duration": 140 ,
    "age_rating": 10
}


### 
PUT http://localhost:3000/filmes/1
Content-Type: application/json

{
    "title": "Vingadores: Ultimato (Edição Estendida)",
    "genre": "Ação e Fantasia",
    "duration": 190,
    "age_rating": 14
}


### 
DELETE http://localhost:3000/filmes/1